In [38]:
import json
import pandas as pd

In [37]:
data = json.load(open('jobs_3217160_results_TrraficFlowAnalysis.json'))

In [39]:
segment_results = []
for route in data['routes']:
    for segment in route['segmentResults']:
        try:
            segment_dict = {
                'segmentId': segment['segmentId'],
                'newSegmentId': segment['newSegmentId'],
                'speedLimit': segment['speedLimit'],
                'frc': segment['frc'],
                'streetName': segment['streetName'],
                'distance': segment['distance'],
                'shape': segment['shape']
            }
        except:
            pass
        segment_results.append(segment_dict)
        
df_segment_results = pd.DataFrame(segment_results)

In [41]:
df_segment_results

,segmentId,newSegmentId,speedLimit,frc,streetName,distance,shape
0,13560331773648,9cd323e1-ae62-4f45-bd94-d90338371422,50,1,Maligaon Baihata Highway,88.98,"[{'latitude': 26.15539, 'longitude': 91.67616}..."
1,13560331813595,99a2336c-0409-4d5f-b365-9f13984d734e,50,1,Maligaon Baihata Highway,29.88,"[{'latitude': 26.15598, 'longitude': 91.67557}..."
2,13560008177148,00004e30-3600-0400-0000-000000e659c1,50,1,Maligaon Baihata Highway,128.42,"[{'latitude': 26.15615, 'longitude': 91.67534}..."
3,13560331813609,b05e17c0-cc55-4d33-8332-c52fcd1beff4,50,1,Maligaon Baihata Highway,78.26,"[{'latitude': 26.15688, 'longitude': 91.67434}..."
4,13560331779532,c087c177-52a4-411e-9739-694c4d2def89,50,1,Maligaon Baihata Highway,45.29,"[{'latitude': 26.15734, 'longitude': 91.67375}..."
...,...,...,...,...,...,...,...
184,13560009824743,00004e30-3600-0400-0000-000000e6b8a6,70,1,NH27,417.67,"[{'latitude': 26.11558, 'longitude': 91.81122}..."
185,13560012586460,00004e30-3600-0400-0000-000000eba4df,70,1,NH27,188.16,"[{'latitude': 26.11749, 'longitude': 91.81478}..."
186,13560010384391,00004e30-3600-0400-0000-000000eba4e4,70,1,NH27,32.32,"[{'latitude': 26.1183, 'longitude': 91.81643},..."
187,13560010384391,00004e30-3600-0400-0000-000000eba4e4,70,1,NH27,32.32,"[{'latitude': 26.1183, 'longitude': 91.81643},..."
188,13560010384391,00004e30-3600-0400-0000-000000eba4e4,70,1,NH27,32.32,"[{'latitude': 26.1183, 'longitude': 91.81643},..."

In [42]:
segment_time_results = []
for route in data['routes']:
    for segment in route['segmentResults']:
        for segment_time in segment['segmentTimeResults']:
            segment_time_dict = {
                'segmentId': segment['segmentId'],
                'timeSet': segment_time['timeSet'],
                'dateRange': segment_time['dateRange'],
                'harmonicAverageSpeed': segment_time['harmonicAverageSpeed'],
                'medianSpeed': segment_time['medianSpeed'],
                'averageSpeed': segment_time['averageSpeed'],
                'standardDeviationSpeed': segment_time['standardDeviationSpeed'],
                'travelTimeStandardDeviation': segment_time['travelTimeStandardDeviation'],
                'sampleSize': segment_time['sampleSize'],
                'averageTravelTime': segment_time['averageTravelTime'],
                'medianTravelTime': segment_time['medianTravelTime'],
                'travelTimeRatio': segment_time['travelTimeRatio'],
                'speedPercentiles': segment_time['speedPercentiles']
            }
            segment_time_results.append(segment_time_dict)
            
df_segment_time_results = pd.DataFrame(segment_time_results)

In [46]:
df_segment_time_results

,segmentId,timeSet,dateRange,harmonicAverageSpeed,medianSpeed,averageSpeed,standardDeviationSpeed,travelTimeStandardDeviation,sampleSize,averageTravelTime,medianTravelTime,travelTimeRatio,speedPercentiles
0,13560331773648,2,1,24.67,31.6,31.20,9.63,27.68,10380,12.98,10.14,1.0,"[15, 19, 22, 24, 26, 27, 29, 30, 31, 32, 33, 3..."
1,13560331813595,2,1,28.83,37.2,36.42,10.62,7.24,10613,3.73,2.89,1.0,"[18, 23, 26, 29, 31, 32, 34, 35, 36, 37, 38, 3..."
2,13560008177148,2,1,34.65,41.2,40.39,10.38,17.43,10313,13.34,11.22,1.0,"[22, 28, 31, 33, 35, 36, 38, 39, 40, 41, 42, 4..."
3,13560331813609,2,1,34.08,41.7,40.54,11.45,10.03,10214,8.27,6.76,1.0,"[21, 26, 29, 31, 33, 35, 37, 39, 40, 42, 43, 4..."
4,13560331779532,2,1,29.99,40.6,40.26,11.66,12.55,15532,5.44,4.02,1.0,"[22, 27, 30, 32, 34, 35, 37, 38, 39, 41, 42, 4..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,13560009824743,2,1,48.26,53.0,52.56,12.84,13.25,7509,31.16,28.37,1.0,"[30, 37, 41, 43, 45, 47, 49, 50, 52, 53, 54, 5..."
185,13560012586460,2,1,29.34,39.0,37.56,13.93,19.66,7528,23.09,17.37,1.0,"[12, 17, 22, 25, 29, 31, 34, 36, 37, 39, 41, 4..."
186,13560010384391,2,1,10.82,21.1,22.69,14.89,13.72,7407,10.75,5.51,1.0,"[3, 4, 6, 8, 10, 13, 15, 17, 19, 21, 23, 26, 2..."
187,-13560011632446,2,1,14.90,24.4,24.56,12.37,3.00,7909,1.72,1.05,1.0,"[6, 9, 12, 14, 16, 18, 20, 21, 23, 24, 26, 27,..."
188,13560012586486,2,1,21.29,25.6,26.64,10.98,77.03,2013,95.39,79.33,1.0,"[11, 14, 15, 17, 19, 20, 22, 23, 24, 26, 27, 2..."